### PR TITLE
Fix bug passing parameters within userauth.py

### PR DESCRIPTION
**Pull request by nagem**

### CODE REVIEW

**Comment by gsfr** [comment]
Are we good to go here? Looks like a trivial change to me.

**Comment by rentzso** [comment]
LGTM

**Comment by coltonlw** [comment]
@gsfr Megan's waiting on me to submit a test for this issue, specifically the abao test to validate the response of the list users endpoint against the raml output schema which is how we discovered the bug.  I plan to submit that shortly, before I leave today

**Comment by coltonlw** [comment]
LGTM

**Pull request merged**
