### PR TITLE
Add PR guidelines

### PR DESCRIPTION
**Pull request by coltonlw**
This adds a pull request template with a checklist for the reviewer(s)

Also updates CONTRIBUTING.md to add standards for testing

### CODE REVIEW

**Comment by gsfr** [comment]
Thanks, @coltonlw. I'm not sold on needing a checklist for reviewers (us), though. Maybe a checklist for contributors makes more sense, but even that seems a little premature.

Updates to CONTRIBUTING.md are good, except that you're missing a newline before `### Docstrings`.

**Comment by coltonlw** [comment]
@gsfr The checklist makes it clear it's the reviewers responsibility to verify the changes.  Even though some of the items are listed in the code standards the checklist let's the reviewer know which things are the most important to check for.  It also helps guide the review process itself to ensure consistent reults, such as the item for giving detailed explanations when making notes about a change.

**Comment by coltonlw** [comment]
@gsfr I updated the PR template so it's a list of tips instead of a checklist.  My main goal here is to encourage us to start adding tests with each change we make.

**Comment by gsfr** [comment]
LGTM

**Comment by kofalt** [comment]
I'm not a huge fan of these in OSS, because I want a project to be welcoming and present an unassuming and low barrier to first contact. In my opinion, a internal contributor will already know about these, and an external contributor should feel free to not follow them & receive feedback in the review instead.

That said, the fact that it's only a PR (not issue) template, and the fact that it's not a set of checkboxes, makes me okay with this landing if ya'll are into it :)

**Comment by ryansanford** [comment]
@coltonlw 
I'd drop the "using clear language and technical terms" from the PR template, due to its subjective nature, though not a deal breaker for me. Otherwise LGTM.

**Pull request merged**
