### PR TITLE
add mimetype for each file in mongo

### LINKED ISSUE #153: Type conflating with MIME type
Ref #151 about `type: "gif"` being returned on a container's file:

1. `gif` isn't a mime type (contrast `image/gif`)
1. This field is also used for scientific data types (`dicom`)

This is troublesome when trying to make UI-relevant decisions (deciding if a viewer icon should be visible, which viewer to launch, etc).

My proposal:

1. The `type` field is only used for scientific data - so, `dicom` and similar. Blank (empty string) if there isn't a scientific data type flagged on this file.
1. A new `mime` field is sent on all files (data and attachments) that has a best-guess mimetype on it. Defaults to `application/octet-stream`.

Thoughts? @mrDarcyMurphy @dpuccetti-flywheel

### PR DESCRIPTION
**Pull request by rentzso**
closes #153

### CODE REVIEW

**Comment by kofalt** [comment]
LGTM :+1:

**Comment by gsfr** [comment]
LGTM.

Do we prefer `type` and `mimetype` over `type` and `mime`? I'm fine with either.

**Comment by rentzso** [comment]
I would keep ```mimetype``` if it's fine for everybody

**Comment by kofalt** [comment]
`type` and `mimetype` are fine by me. Merging

**Pull request merged**
