### PR TITLE
Use (now available) pypi tempfile backport

### PR DESCRIPTION
**Pull request by ambrussimon**
Found 3rd party "official" backport of py3 tempfile.

### Review Checklist

- Tests were added to cover all code changes
- Documentation was added / updated
- Code and tests follow standards in CONTRIBUTING.md

### CODE REVIEW

**Comment by kofalt** [comment]
This brings back the log spam :pensive: 
https://travis-ci.org/scitran/core/builds/348324143#L1304

But whatever lol.

**Comment by gsfr** [comment]
Would be good to silence those warnings. @ambrussimon Worth subclassing?

**Comment by ambrussimon** [comment]
@kofalt Thanks for catching that regression. Fixed by disabling warnings with that message.

Also, polling for opinions here about further decreasing test output noise;
What do you think about getting rid of the log lines reporting `Initialized request ...`, at least for tests, using something like `if os.environ.get('SCITRAN_RUNTIME_COVERAGE') == 'true'`? (Alternative suggestions welcome.)

**Comment by kofalt** [comment]
I very much would love for that log line be disabled by default.

**Comment by gsfr** [comment]
I'm definitely in favor of reducing test output noise.

**Pull request merged**
