### PR TITLE
Descriptive error when search is down

### LINKED ISSUE #852: Better error message when elastic connection is unsuccessful
If elastic is down:

```
POST api/dataexplorer/search return_type="file"
```

```json
{
    "message": "ConnectionError(<urllib3.connection.HTTPConnection object at 0x7fdc00428810>: Failed to establish a new connection: [Errno -2] Name or service not known) caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7fdc00428810>: Failed to establish a new connection: [Errno -2] Name or service not known)", 
    "status_code": 500
}
```

Ideally, it would be something more like this:

```js
{
    "message": "Search is currently down. Try again later.",
    "status_code": 503 // <-- note
}
```

### PR DESCRIPTION
**Pull request by hkethi002**
Fixes #852 
### Review Checklist

- Tests were added to cover all code changes
- Documentation was added / updated
- Code and tests follow standards in CONTRIBUTING.md

### CODE REVIEW

**Comment by nagem** [comment]
It would most likely be a `elasticsearch.TransportError`, but a catch-all `elasticsearch.ElasticsearchError` is fine. LGTM.

**Comment by kofalt** [comment]
Question: What would you think of instead adding `ElasticsearchException` (or something more specific) to the global exception handler instead? This method looks brittle in that it depends on a duplicated try/catch with each ES interaction.

**Comment by nagem** [comment]
👍 changes look good

**Comment by kofalt** [comment]
LGTM

**Comment by kofalt** [comment]
Mild retcon - I guess this swallows any ElasticSearch root-cause stack trace, right?

Maybe we want to log those, so that if we get weird ES problems we at least have debug info.

**Pull request merged**
