### PR TITLE
Add ability to archive files

### PR DESCRIPTION
**Pull request by nagem**
### Review Checklist

- Tests were added to cover all code changes
- Documentation was added / updated
- Code and tests follow standards in CONTRIBUTING.md

### CODE REVIEW

**Comment by kofalt** [comment]
Looks like this branch is off another branch - reset?

**Comment by kofalt** [comment]
Code appears to be reset.

PR does not get an LGTM from me, but does get a shrug. Merge as desired.

**Comment by ryansanford** [comment]
@nagem 
Is this change purely additive? Does it align at all with priorities for the next 4 months? Looking for input on abandoning vs. pushing this through. Thanks!

**Comment by nagem** [comment]
Closing this PR as it is covered in new PR separate from classification changes.

**Pull request closed without merging**
