### PR TITLE
Build docs

### LINKED ISSUE #248: Infrastructure for building pydocs
As a scitran/core developer, I want auto generation of the API documentation in place. This enables the successful completion of Enhancement #63

Acceptance criteria:
- Process must work for API endpoints.
- Provide pydoc examples to demonstrate expected usage.
- Doc generation must be automated.
- Must be an entrypoint for document generation locally so pydoc changes can be checked before commit.

Design Notes:
Move forward to

### PR DESCRIPTION
**Pull request by ryansanford**
Resolves #248

Provide script to build code and REST interface docs.

Docs are built using `sphinx-apidoc` and `sphinx-build`  (http://www.sphinx-doc.org/) utilizing the  extensions `sphinx.ext.autodoc` and `sphinxcontrib.httpdomain` (http://pythonhosted.org/sphinxcontrib-httpdomain/).

The scope of this PR is to get the docs building with some examples for the REST interface. Adding the appropriate pydoc to each package/module/class/function is a future TODO.

### Notes
- Python package requirements are in `docs/requirements-docs.txt`
- Building of the HTML docs can be initiated by executing `./docs/build-docs.sh`
- HTML documentation is written to `docs/build/`
- Building and serving the docs is built into the Docker image
- uWsgi in the Docker image is now built with pcre so requests to /api/docs can be redirected cleanly
- No changes are required for the docker entry-point consumers (Flywheel)
- `/api/docs` and `/api/docs/` will redirect to the routing table at `/api/docs/http-routingtable.html`
- The top level project documentation page is served at `/api/docs/index.html`

@gsfr If it will take a while for the run.sh integration, I'd prefer to break that out into a separate task.

@nagem @rentzso Please pull this branch, and let me know if there are any concerns to landing this. Thanks!

### CODE REVIEW

**Comment by gsfr** [comment]
Thanks, @ryansanford. The diff looks harmless to me, although I don't like the huge blob of html in root.py. Any way to factor that out into a separate file?

Don't wait for run.sh. I'll update that when things have stabilized.

**Comment by ryansanford** [comment]
@gsfr : Thanks for the review.

How would you feel about truncating the html response in root.py. The length of the response caught my eye as well, but I thought it would be better to be verbose with the initial examples I added.

Refactoring the blob of html out of root.py might get messy, since you would need to inject that into the function's __doc__ after the fuction is imported by Sphinx. I know this is possible, because I experimented with it for other approaches. The further removed the docs get from the code definition, the higher the bourdon of maintenance.

I played around for a little bit with implementing a `routes` sub-package and moved the individual route definitions from api.py to there. I backed away from that approach for a couple reasons.
- Code changes for this documentation generation PR would now impact every route, increasing significantly the team involvement required to review and test.
- If using docstrings on module data members or class attributes
  - The html docs came out under the name of the data member or class attribute.
  - The docstring was adjacent to the route definition
- If using docstrings on module or class definition
  - Documentation was no longer adjacent to the route definition, since the route docs were one docstring at the top of the module/class
- Increased boilerplate required to add routes, and locations to update on route changes.
- Felt like that kind of code restructure was outside the scope of the source issue #248 which was to quickly implement the doc generation.

**Comment by gsfr** [comment]
> How would you feel about truncating the html response in root.py.

Go for it.

**Comment by ryansanford** [comment]
@nagem @rentzso This is rebased, and the html response in root.py is now an excerpt. If launching from the flywheel environment, use the `-b` flag to force a rebuild of the docker image which is required for the /api/docs routing.

Let me know if there are concerns with landing this end of day tomorrow.

**Comment by nagem** [comment]
I'll make time to look over it tomorrow, thanks @ryansanford

**Comment by rentzso** [comment]
From a very quick look LGTM.
Thanks @ryansanford

**Pull request merged**
