### PR TITLE
Encrypt travis variable

### LINKED ISSUE #542: Sensitive travis variables need to be encrypted
Convert sensitive travis variables to be encrypted. Currently, only the dockerhub trigger URL needs to be converted.

### PR DESCRIPTION
**Pull request by ryansanford**
Resolves #542 

### Review Checklist

- Tests were added to cover all code changes
- Documentation was added / updated
- Code and tests follow standards in CONTRIBUTING.md

### CODE REVIEW

**Comment by ryansanford** [comment]
@gsfr 
This PR is in response to https://github.com/scitran/core/pull/533#issuecomment-253057711

I did test a tag push, and the trigger URL still works after being encrypted. That variable is gone from the travis settings, so no dockerhub triggers will fire until this is merged.

**Comment by gsfr** [comment]
Don't we want this in `env.global` instead of `env.matrix`?

**Comment by ryansanford** [comment]
@gsfr Good catch. Fixing...

**Comment by ryansanford** [comment]
@gsfr My tests pass. I'll merge.

**Pull request merged**
