### PR TITLE
Replace coveralls with codecov

### LINKED ISSUE #910: Enable coverage reporting/checking on PR diff
Spinoff of PR #891

Coveralls doesn't report or easily convey the coverage on the PR Diff. This is important for easily confirming the coverage of new/modified lines of a PR independent of the global coverage increase/decrease.

Coveralls also doesn't overlay line diff with the coverage diff for an efficient deeper analysis.

Suggest converting to codecov which can address both of these concerns.

### PR DESCRIPTION
**Pull request by ryansanford**
Resolves #910 

TODO:
- [x] Replacing badge TBD when url is known
- [ ] Confirm 100% coverage on diff required for success/green is acceptible

### Review Checklist

- Tests were added to cover all code changes
- Documentation was added / updated
- Code and tests follow standards in CONTRIBUTING.md

### CODE REVIEW

**Comment by kofalt** [comment]
Suggestion: Add an otherwise-empty commit to master that turns on codecov to fix this PR's "Missing base commit" problem. Then we'd see the statuses.

image

**Comment by ryansanford** [comment]
@nagem You ok with me pushing the codecov upload to .travis.yml on master. REL Kofalt's suggestion

**Comment by nagem** [comment]
@ryansanford Go ahead!

**Comment by ryansanford** [comment]
After rebase of this branch, the codecov comment is updated, but the PR lost the codecov result. I'll close and re-open to see if that addresses this issue.

screen shot 2017-09-19 at 12 40 46 pm

**Comment by ryansanford** [comment]
Based on previous discussion with Megan, merging as-is and will tweak behavior from there.

**Pull request merged**
