### PR TITLE
Adapt to new reaper calling convention

### PR DESCRIPTION
**Pull request by gsfr**
@ryansanford Further changes required...

### Review Checklist

- Tests were added to cover all code changes
- Documentation was added / updated
- Code and tests follow standards in CONTRIBUTING.md

### CODE REVIEW

**Comment by ryansanford** [comment]
@gsfr 
Sorry for the delay on acting on this. The intention is that the env var `SCITRAN_SITE_API_URL` should no longer include the `/api` as that segment will now always be assumed? This will be a breaking change with some DEV and PROD infra, so merge and release coordination will be necessary. I think next week would be realistic for making that happen.

**Comment by gsfr** [comment]
@ryansanford That's right. Sounds good.

**Comment by gsfr** [comment]
Rebased.

**Comment by gsfr** [comment]
Closing in agreement with @ryansanford.

**Pull request closed without merging**
