### PR TITLE
Fix loading of analyses in gear suggest endpoint

### PR DESCRIPTION
**Pull request by nagem**
Fixes #899 

Analyses used to be attached to containers, now they need to be loaded separately. 

### Review Checklist

- Tests were added to cover all code changes
- Documentation was added / updated
- Code and tests follow standards in CONTRIBUTING.md

### CODE REVIEW

**Comment by nagem** [comment]
Small change, will merge when CI is green

**Comment by ryansanford** [comment]
@nagem Can we get a test that will catch this type of regression in the future?

**Comment by nagem** [comment]
@ryansanford Writing a test would have taken 10x the time it took to fix it, so I wanted to get that part of the change merged first. I'll add a test in a followup PR.

**Comment by lmperry** [comment]
@ryansanford can you ping me and @tcbtcb when there is a release with this patch? Columbia and VA Palo Alto need this.

**Pull request merged**
