### PR TITLE
Adapt to new gears package naming

### PR DESCRIPTION
**Pull request by gsfr**
I [renamed](https://github.com/flywheel-io/gears/pull/6) the flywheel/gears Python package from `gear_tools` to `gears`. This PR deals with the resulting name collision here. No functional change.

https://github.com/flywheel-io/gears/pull/6 needs to land first, and then `requirements.txt` needs to be updated before merging this.
### Review Checklist
- Tests were added to cover all code changes
- Documentation was added / updated
- Code and tests follow standards in CONTRIBUTING.md

### CODE REVIEW

**Comment by gsfr** [comment]
@nagem, @ryansanford Can we aim to land this PR during the current sprint?

**Comment by ryansanford** [comment]
@gsfr Can you rebase this to resolve the conflicts? I can pick up the build and release testing. I think the old gear builder would have been impacted by the flywheel-io/gears change, but that is now obsolete.

**Comment by gsfr** [comment]
@ryansanford We should be good to go, pending flywheel-io/gears#6 and a quick update to `requirements.txt`.

**Comment by ryansanford** [comment]
Testing this now. Need to make a fly/fly change first due to stale gears.pyc file after the rename.

**Comment by ryansanford** [comment]
@nagem Can you do a code review on this? My functional testing of adding and executing gears has been successful after merging https://github.com/flywheel-io/gears/pull/6 and updating the reference with my last commit.

**Comment by nagem** [comment]
I did one when the PR was originally opened and it looked good. I'll do another one now to be sure.

**Comment by kofalt** [comment]
I suppose we could tag a release each time we update our usage in the core. Right now I'm comfortable using a commit, given how rarely it changes and small surface area.

**Comment by nagem** [comment]
LGTM.

**Comment by kofalt** [comment]
Whoop! This has been superseded & taken care of by another PR. :beer:

**Comment by ryansanford** [comment]
@gsfr Any objections to deleting this branch? Alternate resolution to the naming conflict went into this PR: https://github.com/scitran/core/pull/685/files

**Comment by gsfr** [comment]
@ryansanford Yes, I object. This is a proper solution, while @kofalt's patch is pragmatic, but a hack nonetheless.

**Comment by gsfr** [comment]
I'm happy to resolve the conflicts if we agree to actually land it this time.

**Comment by gsfr** [comment]
Closing in agreement with @ryansanford.

**Pull request closed without merging**
