### PR TITLE
Update to newman 3.1.0 and collection format v2

### PR DESCRIPTION
**Pull request by coltonlw**
Update to newman 3.1.0 and collection format v2

Fixes: #463

### CODE REVIEW

**Comment by ryansanford** [comment]
@coltonlw 
Please update newman to the same version in `test/bin/setup-integration-tests-ubuntu.sh` and `test/Dockerfile`

Anything else I should look for other than confirming the new newman is installed?

**Comment by coltonlw** [comment]
@ryansanford Nice catch that I didn't update the ubuntu setup script as well!  To prevent this in the future, I've added npm's [package.json](https://docs.npmjs.com/files/package.json) in the integration_tests folder.  Now the integration test setup process for each platform install dependencies from this same file.  You could check that this will work for the test/Dockerfile process.  Thank you

**Comment by coltonlw** [comment]
@ryansanford I have a couple things to work out still I'll let you know when the branch is stable

**Comment by coltonlw** [comment]
@ryansanford This branch is stable

**Pull request merged**
