### PR TITLE
return JSON responses for errors

### LINKED ISSUE #59: All responses, including all errors, should be in JSON format
Single exception: ```GET /api``` will return HTML for human consumption.

For errors, emit a predictable error struct.

### PR DESCRIPTION
**Pull request by rentzso**
closes #59

### CODE REVIEW

**Comment by rentzso** [comment]
for reference I followed this to handle errors:
https://webapp-improved.appspot.com/guide/exceptions.html

and this to handle routing errros:
https://webapp-improved.appspot.com/api/webapp2.html#webapp2.Router.default_dispatcher

**Comment by kofalt** [comment]
Excellent and LGTM :+1: 

One quick question, about logic that pre-dates this PR:

```python
rv = router.default_dispatcher(request, response)
if rv is not None:
     response.write(json.dumps(rv, default=util.custom_json_serializer))
     response.headers['Content-Type'] = 'application/json; charset=utf-8'

```

In what scenario is rv None? Why don't we do anything when happens?

**Comment by gsfr** [comment]
> In what scenario is rv None? Why don't we do anything when happens?

When `rv` is `None`, we expect the request handler to have already written the response. `Root.get()` may be the only occurrence of that.

**Comment by gsfr** [comment]
:+1: Merge as desired.

**Pull request merged**
