### PR TITLE
Record coverage for integration tests

### PR DESCRIPTION
**Pull request by coltonlw**
Adds integration tests to coverage metric

Prints coverage report after running test on ubuntu or osx

Fixes: #487 

### Review Checklist

- Tests were added to cover all code changes
- Documentation was added / updated
- Code and tests follow standards in CONTRIBUTING.md

### CODE REVIEW

**Comment by coltonlw** [comment]
coverage/coveralls — Coverage increased (+34.2%) to 40.985%   🎉 🎈

**Comment by gsfr** [comment]
This is great!

I'm seeing this towards the end of the process:
```
./bin/run-dev-osx.sh: line 110: 69062 Abort trap: 6           mongod --port $SCITRAN_PERSISTENT_DB_PORT --dbpath "$SCITRAN_PERSISTENT_DB_PATH" --smallfiles
worker 1 buried after 2 seconds
goodbye to uWSGI.
./test/bin/run-tests-osx.sh: line 14: 69052 Terminated: 15          SCITRAN_RUNTIME_PORT=8081 SCITRAN_CORE_DRONE_SECRET=integration-tests SCITRAN_RUNTIME_COVERAGE="true" ./bin/run-dev-osx.sh -T -U -I
```

Also, wouldn't it be better to `wait` for the API to terminate instead of doing a `sleep 2`?

Wonder if [this thread](http://veithen.github.io/2014/11/16/sigterm-propagation.html) might somehow help.

**Comment by coltonlw** [comment]
@gsfr wait is definitely better, updated with that change

**Comment by nagem** [comment]
This LGTM, too. Nice to see the hard work pay off in the stats 💯.

**Comment by coltonlw** [comment]
@gsfr Related to "abort trap: 6" output on osx, I was able to clean that up simply by putting "wait" before removing the mongo data directory, instead of after.  Previously mongo was in the process of a shutdown when we deleted the data directory.  Good to go on this then?

**Comment by coltonlw** [comment]
Rebased against master

**Comment by gsfr** [comment]
Thanks, @coltonlw.

I'm still seeing the following, which I don't understand:
```
./test/bin/run-tests-osx.sh: line 16: 85007 Terminated: 15          SCITRAN_RUNTIME_PORT=8081 SCITRAN_CORE_DRONE_SECRET=integration-tests SCITRAN_RUNTIME_COVERAGE="true" ./bin/run-dev-osx.sh -T -U -I
```

Would be nice if we could shutdown our server and exit cleanly.

**Comment by coltonlw** [comment]
@gsfr We are shutting down the server cleanly, that message is "wait" builtin / bash telling you the child process  running "run-dev-osx.sh" was terminated by signal 15 (sigterm)

**Comment by coltonlw** [comment]
@gsfr "wait 2> /dev/null", removing prod requirements from integration test requirements.txt,  and separating unit + integration test coverage (plus reporting only integration tests to coveralls) is complete

**Comment by gsfr** [comment]
LGTM, other than the errant newline addition in TESTING.md. Nice work!

**Pull request merged**
