### PR TITLE
Tolerate invalid gear data during v22 upgrade

### PR DESCRIPTION
**Pull request by kofalt**
This will allow the database to proceed with invalid job records, creating empty gear documents when no such referenced document exists. The empty gears have `custom.flywheel.invalid` set to true, and will be disallowed from entering into the jobs queue.

### Review Checklist

- Tests were added to cover all code changes
- Documentation was added / updated
- Code and tests follow standards in CONTRIBUTING.md

### CODE REVIEW

**Comment by nagem** [comment]
Once-over LGTM after pair programming.

**Comment by ryansanford** [comment]
We need some type of progress indication due to the long duration on larger DBs. Some type of print which phase we're on, and intermediate prints within each phase. 

Something like...
```
Upgrade 22 phase 1 of 3 Updating gears
...
Upgrade 22 phase 2 of 3 Updating jobs
Processed job 0 of 24,567
Processed job 100 of 24,567
Processed job 200 of 24,567
...
Upgrade 22 phase 3 of 3 Updating batch
...

```

**Comment by kofalt** [comment]
Added progress indication:

```
Upgrade v22, phase 1 of 3, upgrading gears...
  Updated gear 58a7884a830ab5001c06821a ...
  Updated gear 58a7884a830ab5001306821a ...
  Updated gear 58a7884a830ab5001806821a ...
  Updated gear 58a7884a830ab5001806821b ...
  Updated gear 58a7884a830ab5001c06821b ...
Upgrade v22, phase 2 of 3, upgrading jobs...
  Processed 10 jobs of 135...
  Processed 20 jobs of 135...
  Processed 30 jobs of 135...
  Processed 40 jobs of 135...
  Processed 50 jobs of 135...
  Processed 60 jobs of 135...
  Processed 70 jobs of 135...
  Processed 80 jobs of 135...
  Processed 90 jobs of 135...
  Processed 100 jobs of 135...
  Processed 110 jobs of 135...
  Processed 120 jobs of 135...
  Processed 130 jobs of 135...
Upgrade v22, phase 3 of 3, upgrading batch...
Upgrade v22, complete.
```

No functionality change. This example was reporting every 10; in the commit it's 1000.

**Comment by ryansanford** [comment]
@dpuccetti Gear field to check for related to hiding is `gear.custom.flywheel.invald`. custom and below may not exist, so null checks are advised.

**Comment by ryansanford** [comment]
LGTM after testing latest push.

**Pull request merged**
