### PR TITLE
fix search for groups

### PR DESCRIPTION
**Pull request by rentzso**
A simple search for all groups (without the all_data flag) doesn't
return any result.

### Review Checklist

- Tests were added to cover all code changes
- Documentation was added / updated
- Code and tests follow standards in CONTRIBUTING.md

### CODE REVIEW

**Comment by kofalt** [comment]
I'm going to let this hang until Megan gets back, unless it's urgent! Let me know if it is.

**Comment by rentzso** [comment]
I don't think it is urgent. It's not deployed anywhere, I guess. Just wanted to create the PR...

**Comment by nagem** [comment]
LGTM!

**Comment by nagem** [comment]
Hey Renzo I'm going to merge this one, thanks for the fix!

**Pull request merged**
