### PR TITLE
Remove api loopback request for schema ref resolution

### PR DESCRIPTION
**Pull request by nagem**
Addresses half of #226.

Also made a small bug fix to `download.json`.

### CODE REVIEW

**Comment by coltonlw** [comment]
I know user schema ref's the avatar schema, it would be nice if we had some tests for these endpoints and you could wait a week or so until we do to merge this.  Otherwise LGTM

**Comment by nagem** [comment]
It'll be nice when I don't have to manually test these, though 😄

**Comment by coltonlw** [comment]
:octocat: yes it will, hopefully soon

**Comment by rentzso** [comment]
LGTM!

**Pull request merged**
