### PR TITLE
Store inputs on analyses objects

### PR DESCRIPTION
**Pull request by nagem**
To aid in searching analyses objects, we will store the job inputs as file objects on the analyses object.

### CODE REVIEW

**Comment by kofalt** [comment]
I'm not thrilled by duplication, but Megan's convinced me for now. Diff tentatively looks good but I defer to @rentzso for review.

If we merge this, I would like to see a ticket filed that tracks either the removal of this duplication or the conclusion that we'll keep duplicating in this & other cases. My understanding is that empowering the mongo connector to use the core (import via requirements.txt? merge repos?) could avoid this in the long run.

**Comment by nagem** [comment]
@kofalt another option you and I discussed was the possibility of the mongo-es replicator calling the API to get the correct format it needs.

**Comment by rentzso** [comment]
To clarify, one of the reasons for this change is that it gives a more consistent and self-contained format to each analysis in the database. 
This enable tools like mongo connectors to read directly the mongo oplog, and to replicate asynchronously but almost instantly the state of the database without any additional load on the API (@megan calling the API to replicate all the records could be ok, but I think it would be better to avoid any additional overload, and also someone will have to write all the code, almost from scratch, to export data from mongo to elasticsearch).

I am not sure that the merge solution will be very practical either: let's say that we need another tool that reads from the oplog. This tool code will also need to be merged to core, and so on...

Data duplication seems the lesser evil, but @kofalt feel free to open a ticket to investigate on this and on the possible implications of data duplication.

**Comment by rentzso** [comment]
LGTM!

**Comment by nagem** [comment]
Retested the db update script, everything looks good. Merging now.

**Pull request merged**
