### PR TITLE
Define supported dockerized test execution

### PR DESCRIPTION
**Pull request by ryansanford**
Resolves: #474 

**Changes in this PR**
- Remove `test/Dockerfile`
- Add test requirements to `Dockerfile`
- Update Testing instructions for dockerized execution of tests

### CODE REVIEW

**Comment by ryansanford** [comment]
@coltonlw 
Please confirm additions to TESTING.md are appropriate, and work in your environment. Thanks.

**Comment by coltonlw** [comment]
@ryansanford The changes look good to me, possibly consider making a shell script or docker compose to run these in 1 shot.  Also docker has never worked on my macbook so I can't test on there

**Comment by ryansanford** [comment]
Execution of tests via docker image has now been scripted. Also merged in change from @coltonlw  to resolve .pyc caching errors.

**Comment by ryansanford** [comment]
Got a verbal LGTM from @coltonlw . Merging now.

**Pull request merged**
