### PR TITLE
Add rule regex input validation

### PR DESCRIPTION
**Pull request by ambrussimon**
Added tests as well. 
@dpuccetti here's a full sample response to the [test payload](https://github.com/scitran/core/pull/999/files#diff-c75df6e24d39da012391728350be5e06R39):
```
{
    'status_code': 422,
    'message': 'Validation Error.',
    'reason': 'Cannot compile regex patterns',
    'patterns': [u'^(?non-image$).+']
}
```

### Review Checklist

- Tests were added to cover all code changes
- Documentation was added / updated
- Code and tests follow standards in CONTRIBUTING.md

### CODE REVIEW

**Comment by nagem** [comment]
Looks like one of the dependencies failed to load in one of the Travis builds, I restarted it. 

Changes look good to me, though.

**Comment by ambrussimon** [comment]
@nagem Thanks! I was looking around on the Travis UI, but didn't find that feature. How do you do a restart?

**Comment by nagem** [comment]
@ambrussimon there is an option in the upper right:
screen shot 2017-11-16 at 12 00 25 pm

You do needed to be logged in with your Github account on Travis, though. I think that's what gives you the permission.

**Comment by ryansanford** [comment]
@dpuccetti I switched my reviewer slot to you. So we can hopefully wrap this up today, tag @nagem if you find issues.

**Pull request merged**
