### PR TITLE
Advanced search + Analyses

### PR DESCRIPTION
**Pull request by rentzso**
Changes proposed in this pull request:
- add ElasticSearch advanced search
- add endpoint to add analyses to sessions, acquisitions, collections, projects

@nagem @gsfr could you review this? Search on notes depends on this change https://github.com/flywheel-io/flywheel/pull/207
It won't return an error though, just no result.

### CODE REVIEW

**Comment by gsfr** [comment]
Looks like a low-risk, but very large change set. Can we split this out into two PRs: one for ES and one for analyses?

**Comment by rentzso** [comment]
created the first PR for search: https://github.com/scitran/core/pull/310

**Comment by rentzso** [comment]
created the second PR https://github.com/scitran/core/pull/311

**Comment by rentzso** [comment]
closing as it was replaced by #310 and #311 

Please do not delete `st_prototype` branch

**Pull request closed without merging**
