### PR TITLE
Project rules

### LINKED ISSUE #720: Automatic gear rules on the project level
Will replace site-level rules.

Endpoint spec follows: 

```python

GET    api/projects/<x>/rules

returns [
	{ '_id': 1 },
	{ '_id': 2 },
]

POST   api/projects/<x>/rules
{
	'alg': 'my-gear-name',

	'name': 'whatever',

	'any': [],

	'all': [
		{
			'type': 'file.type',
			'value': 'nifti'
		},
		{
			'type': 'file.measurements',
			'value': 'functional'
		}
	]
}
returns { '_id': 37 } 200

GET    api/projects/<x>/rules/<y>

returns { '_id': 'y' } 200

PUT    api/projects/<x>/rules/<y> (replace)

wholesale replace, 200

DELETE api/projects/<x>/rules/<y>

returns 200

obj = {
	'_id': 'SOME_ID',

	'project_id': 'SOME_FK',

	'alg': 'my-gear-name',

	'any': [],

	'all': [
		{
			'type': 'file.type',
			'value': 'nifti'
		},
		{
			'type': 'file.measurements',
			'value': 'functional'
		}
	]
}
```

### PR DESCRIPTION
**Pull request by kofalt**
Closes #720. Ref that ticket for endpoint spec.

Tested as valid via job counts on example data set with their rules:

```
# Before
"cancelled": 0   --> "cancelled":   0
"complete":  0   --> "complete":  135
"failed":    0   --> "failed":      0
"pending":  74   --> "pending":     0
"running":   0   --> "running":     0

# After
"cancelled": 0   --> "cancelled":   0
"complete":  0   --> "complete":  135
"failed":    0   --> "failed":      0
"pending":  74   --> "pending":     0
"running":   0   --> "running":     0
```

Upgrade script takes global rules and sets them on every project.
Thereafter, new projects should add rules for any gears they wish to trigger.

CI will not pass on the old infra due to endpoints changing as per above spec.

### Review Checklist

- Tests were added to cover all code changes
- Documentation was added / updated
- Code and tests follow standards in CONTRIBUTING.md

### CODE REVIEW

**Comment by ryansanford** [comment]
@kofalt 
We do want raml and tests. Want to attend our morning sync with Ambrus for assistance? Looks like our CI here is currently failing due to unit tests.

I'll tackle changing the site-level rule loading infra tomorrow.

**Comment by kofalt** [comment]
Tentative on morning sync. I don't know what my schedule will be like :slightly_smiling_face:

**Comment by kofalt** [comment]
Rebased & updated

**Comment by nagem** [comment]
Thanks for adding some tests/raml.

Looking it over it looks good.

**Pull request merged**
