### PR TITLE
Added optional operator key for sessions

### LINKED ISSUE #980: Make Session Operator a first-class attribute
@nagem Please confirm design considerations.

Key name?
Key value type? 
Session level only?
Value required?

### PR DESCRIPTION
**Pull request by hkethi002**
Fixes #980 
### Review Checklist

- Tests were added to cover all code changes
- Documentation was added / updated
- Code and tests follow standards in CONTRIBUTING.md

### CODE REVIEW

**Comment by nagem** [comment]
LGTM

**Comment by nagem** [comment]
Some of your questions are in the linked ticket, but to answer the rest - anyone with write can edit this field, it is not a UID (it's just an opaque string), and it would get returned on list endpoints.

**Comment by nagem** [comment]
It's a field that is present in some filetype headers that classifier gears used to set. It was requested that that information is set and viewable in clients. This can (and should) be added to the SDK.

**Comment by kofalt** [comment]
Sounds good! I'll make a branch.

**Comment by kofalt** [comment]
My reading, then:

1. Yes
1. Yes
1. Yes
1. Present
1. No

**Pull request merged**
