### PR TITLE
Only log once per ticket for download

### PR DESCRIPTION
**Pull request by nagem**
### Review Checklist

- Tests were added to cover all code changes
- Documentation was added / updated
- Code and tests follow standards in CONTRIBUTING.md

### CODE REVIEW

**Comment by nagem** [comment]
This is ready to review and merge.

**Comment by ryansanford** [comment]
@nagem 

I'm getting 6 `download_file` events for 30 downloads from a single ticket. Think it's due to multiple request connections on the requester end?

**Comment by nagem** [comment]
@ryansanford Probably, there is a decent chunk of logic between when we get the ticket from the db and when we log. I could do a recheck of whats in the db right before attempting to log but unfortunately there is not an easy way to make sure it's perfect.

**Comment by nagem** [comment]
I thought of another option - I could set the ticket id on the log message and then use $setOnInsert to make it reasonably atomic. We'd need an index on ticket_id to make it reasonably fast.

**Comment by ryansanford** [comment]
@nagem I'm still getting 6 logging events with the same test. If you want to try and reproduce, it's subject 468, and I'm viewing the dicoms for acquisition 468_7_1_t1 in the testdata dataset.

**Comment by nagem** [comment]
@ryansanford this has been modified to ensure only one log per ticket id. The downside being there must be an index for ticket id.

**Comment by kofalt** [comment]
Code in its current state gets a :+1: at a high speed pass :slightly_smiling_face:

**Comment by ryansanford** [comment]
Current commit behaves great. Only 1 entry per ticket now.

`ticket_id` at the root level feels odd to me, given that it's only valid for downloads. Objections to moving it under the `context` object @nagem ?

Otherwise, LGTM

**Comment by nagem** [comment]
Thanks for reviewing! I'll move it to context. One additional change I'm going to make per my discussion yesterday with mgmt is adding `subject.id` and `subject.code` to the context, since most searching will be done from the context of "Who looked at this subject's data?" and it would be better if we didn't have to tease out the sessions that matter from a separate search.

**Comment by ryansanford** [comment]
Functionality looks good to me from with the latest commit. Feel free to merge after CI failures are addressed.

**Pull request merged**
