### PR TITLE
Snapshots

### PR DESCRIPTION
**Pull request by rentzso**
The main goal of this change is to enable a client to take a copy(snapshot) of a project at a certain point in time.
All the ids of project, sessions and acquisitions are changed. The key of the original project is stored in the key 'original' of its copy.

Snapshots are essentially immutable. They can be removed, but the only property that can be modified is the public flag.

#### create a snapshot for the project \<project_id\>
method: POST 
path: api/snapshots?project=\<project_id\>

#### get all the project snapshots
method: GET
path: api/snapshots/projects

#### get all the snapshots for a project id
method: GET
path: api/projects/\<_id\>/snapshots

#### get the details of a project/session/acquisition that belongs to a snapshot
method: GET
path: api/snapshots/(projects|sessions|acquisition)/\<_id\>

#### get all the sessions in a project snapshot
method: GET
path: api/snapshots/projects/\<project_id\>/sessions

#### get all the acquisitions in a session snapshot
method: GET
path: api/snapshots/sessions/\<session_id\>/acquisitions

#### delete the project snapshot with all its sessions and acquisitions
method: DELETE
path: api/snapshots/projects/\<project_id\>

#### publish or unpublish the project snapshot, all its sessions and acquisitions
method: PUT
path: api/snapshots/projects/\<project_id\>/public
body: {'value': True/False}

### CODE REVIEW

**Comment by kofalt** [comment]
rnkklgokfdokgrt90ytjpo-o=e-i45kp[tr-=54op

**Comment by rentzso** [comment]
TO DO
1. create route to return snapshots for a given project id
2. modify make public route to also unpublish snapshots (shoud be  api/snapshots/projects/<project_id>/public and it should accept a payload)

**Comment by rentzso** [comment]
@kofalt @gsfr the PR is ready to be reviewed.
Please note that I have updated the description after the latest commits.

**Comment by gsfr** [comment]
LGTM.

Although this is a purely additive change at the moment, I want to branch bali before this lands to avoid possible interference as this gets tested and debugged. Let's delay that for the moment, though, and keep this branch until it has seen some testing.

Ping @constellates: Please test and leave feedback here.

**Comment by constellates** [comment]
Apologies for the delay. I've begun testing this branch today and ran into an issue with creating snapshots. I'm following the request listed in the first comment of this thread.

	method: POST 
	path: api/snapshots 
	body: {'project': <project_id>}

It's returning a 404 error with the message 'project is required to create a snapshot'. I believe this line (https://github.com/scitran/api/blob/project_snapshot/api/handlers/snapshothandler.py#L61) is the issue. It looks like it's trying to get the project id from a route param instead of the request body. If I change it to 

    origin_id = self.request.json_body['project']

I can get the log the origin_id and get the project id from the body, but then the request is returning a 500 error from something else.

**Comment by rentzso** [comment]
Sorry Zack. I changed the route specification without updating the description here. It is

#### create a snapshot for the project \<project_id\>
method: POST 
path: api/snapshots?project=\<project_id\>

let me know if you still receive a 500 error. I tested on my local machine and it worked.

**Comment by constellates** [comment]
Yea I'm still getting the same 500 error as when I change the code. Here's the trace from the log.

	  return super(RequestHandler, self).dispatch()
	File "/usr/local/lib/python2.7/dist-packages/webapp2.py", line 572, in dispatch
	  return self.handle_exception(e, self.app.debug)
	File "/usr/local/lib/python2.7/dist-packages/webapp2.py", line 570, in dispatch
	  return method(*args, **kwargs)
	File "/srv/scitran/api/handlers/snapshothandler.py", line 65, in create
      permchecker = self._get_permchecker(container, container)
	File "/srv/scitran/api/handlers/containerhandler.py", line 349, in _get_permchecker
	  permchecker = self.config['permchecker']
	AttributeError: 'SnapshotHandler' object has no attribute 'config'

**Comment by rentzso** [comment]
The bug should be fixed now. Could you retry? 
FYI 
I've just rebased project_snapshot on master

**Comment by constellates** [comment]
Thanks Renzo. That fixed it. I'll continue testing the rest of the snapshot features today and tomorrow and let you know if I run into anything else.

**Comment by constellates** [comment]
Does this update support requesting files for snapshots? I didn't see any mention of it in the documentation comment so I attempted to prefix the files endpoint with snapshots similar to the other endpoints and am getting a 404.

    /api/projects/56aa965323a243430fd5a965/files/README

    /api/snapshots/projects/56aa9ce323a24345d137f6f6/files/README

**Comment by rentzso** [comment]
Only the routes specified in the PR description have been implemented.
But we definitely have to implement routes like `/api/snapshots/projects/56aa9ce323a24345d137f6f6/files/README`

**Comment by constellates** [comment]
Ok. I've made it through testing the rest of the currently implemented features. I had an issue with updating the public status of a snapshot and deleting a snapshot.

Here's the stack trace for trying to update the public value to true on a snapshot.

    File &quot;/usr/local/lib/python2.7/dist-packages/webapp2.py&quot;, line 1535, in __call__
      rv = self.handle_exception(request, response, e)
    File &quot;/usr/local/lib/python2.7/dist-packages/webapp2.py&quot;, line 1529, in __call__
      rv = self.router.dispatch(request, response)
    File &quot;/srv/scitran/api/api.py&quot;, line 132, in dispatcher
      rv = router.default_dispatcher(request, response)
    File &quot;/usr/local/lib/python2.7/dist-packages/webapp2.py&quot;, line 1278, in default_dispatcher
      return route.handler_adapter(request, response)
    File &quot;/usr/local/lib/python2.7/dist-packages/webapp2.py&quot;, line 1102, in __call__
      return handler.dispatch()
    File &quot;/srv/scitran/api/base.py&quot;, line 128, in dispatch
      return super(RequestHandler, self).dispatch()
    File &quot;/usr/local/lib/python2.7/dist-packages/webapp2.py&quot;, line 572, in dispatch
      return self.handle_exception(e, self.app.debug)
    File &quot;/usr/local/lib/python2.7/dist-packages/webapp2.py&quot;, line 570, in dispatch
      return method(*args, **kwargs)
    File &quot;/srv/scitran/api/handlers/snapshothandler.py&quot;, line 87, in publish
      payload_validator = validators.payload_from_schema_file(self, 'input/public.json')
    File &quot;/srv/scitran/api/validators.py&quot;, line 96, in payload_from_schema_file
      schema = resolver_input.resolve(schema_file)[1]
    File &quot;/usr/local/lib/python2.7/dist-packages/jsonschema/validators.py&quot;, line 336, in resolve
      return url, self._remote_cache(url)
    File &quot;/usr/local/lib/python2.7/dist-packages/functools32/functools32.py&quot;, line 400, in wrapper
      result = user_function(*args, **kwds)
    File &quot;/usr/local/lib/python2.7/dist-packages/jsonschema/validators.py&quot;, line 346, in resolve_from_url
      raise RefResolutionError(exc)
    RefResolutionError: &lt;urlopen error [Errno 2] No such file or directory: '/srv/scitran/api/schemas/input/input/public.json'&gt;

And here's one for snapshot deletion

    File &quot;/usr/local/lib/python2.7/dist-packages/webapp2.py&quot;, line 1535, in __call__
      rv = self.handle_exception(request, response, e)
    File &quot;/usr/local/lib/python2.7/dist-packages/webapp2.py&quot;, line 1529, in __call__
      rv = self.router.dispatch(request, response)
    File &quot;/srv/scitran/api/api.py&quot;, line 132, in dispatcher
      rv = router.default_dispatcher(request, response)
    File &quot;/usr/local/lib/python2.7/dist-packages/webapp2.py&quot;, line 1278, in default_dispatcher
      return route.handler_adapter(request, response)
    File &quot;/usr/local/lib/python2.7/dist-packages/webapp2.py&quot;, line 1102, in __call__
      return handler.dispatch()
    File &quot;/srv/scitran/api/base.py&quot;, line 128, in dispatch
      return super(RequestHandler, self).dispatch()
    File &quot;/usr/local/lib/python2.7/dist-packages/webapp2.py&quot;, line 572, in dispatch
      return self.handle_exception(e, self.app.debug)
    File &quot;/usr/local/lib/python2.7/dist-packages/webapp2.py&quot;, line 570, in dispatch
      return method(*args, **kwargs)
    File &quot;/srv/scitran/api/handlers/snapshothandler.py&quot;, line 80, in remove
      result = permchecker(snapshot.remove)('POST', _id=snap_id)
    File &quot;/srv/scitran/api/auth/containerauth.py&quot;, line 41, in f
      return exec_op(method, _id=_id, payload=payload)
    TypeError: remove() got an unexpected keyword argument 'payload'

All of the other currently implemented snapshotting features appear to be working well and were very straightforward to adapt to our application because of how similar they are to the relevant/pre-existing SciTran endpoints.

**Comment by rentzso** [comment]
@constellates the two bugs on snapshot publishing and deletion are fixed now.

**Comment by constellates** [comment]
I've begun testing the fixes but ran into an issue with group creation after wiping the database. Has the input schema for groups changed in the past few days? Our users creation process involves three requests using shared secret authentication. We create a user, then a group, then add the user as a role on the group.

User creation is still working the same, but group creations returns the following response.

	{
		code: 500,
		uid: null,
		detail: 'None is not of type u\'string\'\n\nFailed validating u\'type\' in schema[u\'properties\'][u\'roles\'][u\'items\'][u\'properties\'][u\'_id\']:\n    {u\'type\': u\'string\'}\n\nOn instance[u\'roles\'][0][u\'_id\']:\n    None'
	}

The group request I'm using is a post to api/groups and has a body with the following structure.

	{
		"_id": "group-name",
		"name": "group-name"
	}

Let me know if you need more details and if you'd prefer I move this to a separate issue.

**Comment by rentzso** [comment]
@constellates I would have expected a 403 as the request doesn't have the user id (uid) sending it. Let me get back to you after I investigate a little more.

**Comment by rentzso** [comment]
now you should get the correct answer (400) as it is interpreted as a public request

**Comment by rentzso** [comment]
I have also added all the integration tests (including yours) to this branch for your convenience.

**Comment by constellates** [comment]
I don't think I fully understand. Am I missing something from that request? I just updated am am still seeing the 500 error.

Here's what I'm seeing in the scitran logs

	2016-02-04 19:03:03      scitran.api                  base.py    80:INFO drone "CRN Server" request accepted
	2016-02-04 19:03:03      scitran.api                  base.py   174:WARN 500 None is not of type u'string'

	Failed validating u'type' in schema[u'properties'][u'roles'][u'items'][u'properties'][u'_id']:
	    {u'type': u'string'}

	On instance[u'roles'][0][u'_id']:
	    None

**Comment by rentzso** [comment]
I see. You are sending a drone request, that has no user.
The group endpoint is expecting a valid user and then it fails.
Fixing it.

**Comment by rentzso** [comment]
@constellates can you please check now?

**Comment by constellates** [comment]
Thanks @rentzso that fix worked for allowing drone based group creation. I'm working on testing the remaining snapshot features now.

**Comment by constellates** [comment]
Everything seems to be working now. Here's a list of actions I've tested today. Let me know if I'm missing anything.
- snapshot creation
- getting snapshot
- getting each snapshot container details to reconstruct bids details
- snapshot deletion
- snapshot publishing/un-publishing
- snapshot file retrieval (not download/ticket)
- getting a list of snapshots
- getting a list of snapshots for a specific project
- snapshot individual file downloads
- snapshot bids downloads
- snapshot symlinked bids downloads

I believe this covers our use cases. Let me know if you need any additional testing from me before merging. And thanks again.

**Comment by constellates** [comment]
I noticed a potential snapshot permission issue today.

    /api/projects/< project ID >/snapshots

This endpoint to get a list of snapshots for a given project appears to rely on the permissions of the project itself. Within our use case projects always remain private and only snapshots can be made public.  

So if a user is viewing a public snapshot they can't get a direct list of sibling snapshots that are also public. If a user makes this request to get the list of snapshots of a project that is private but has public snapshots they currently get the following response.

	{
		"code": 403,
		"uid": null,
		"detail": "this request is not allowed"
	}

Is this the intended functionality? And would it be possible for this to work like the projects GET endpoint where if an authentication header is not supplied it will return all public projects or in this case public snapshots for the intended project? 

There is a possible work around of getting the list of all public snapshots and filtering client side, but it would be nice to keep this on the server for now.

**Comment by rentzso** [comment]
@constellates we didn't think about that use case. If you like, we can return all public snapshots for some project even for a public request.

**Comment by constellates** [comment]
That would we great @rentzso. Thanks.

**Comment by rentzso** [comment]
This has been merged in the bids dedicated fork: https://github.com/poldracklab/bids-core/pull/1
closing

**Pull request closed without merging**
