### PR TITLE
Support unified config

### PR DESCRIPTION
**Pull request by gsfr**
relates to flywheel-io/flywheel#472

### CODE REVIEW

**Comment by ryansanford** [comment]
I'm getting an error with the unit tests when env var `SCITRAN_PERSISTENT_DB_URI=mongodb://scitran-mongo:27017/scitran?replicaSet=elasticflywheel`

@ambrussimon-invenshure I assume this is related to mongomock and not related to the changes within this PR?

```
Running pylint ...
=================================================== test session starts ====================================================
platform linux2 -- Python 2.7.6, pytest-2.8.5, py-1.4.33, pluggy-0.3.1
rootdir: /var/scitran/code/api/test/unit_tests/python, inifile: 
plugins: cov-2.2.0
collected 31 items 

test/unit_tests/python/test_auth.py F..
test/unit_tests/python/test_db_upgrade.py .....
test/unit_tests/python/test_files.py .....
test/unit_tests/python/test_key.py .
test/unit_tests/python/test_request.py ..
test/unit_tests/python/test_rules.py ..........
test/unit_tests/python/test_util.py ....
test/unit_tests/python/test_validators.py .

========================================================= FAILURES =========================================================
______________________________________________________ test_jwt_auth _______________________________________________________

config = AttrDict({'queue': {'max_retries': 3, 'retry_on_fail': False, 'prefetch': Fals...host': 'flywheel-elasticsearch:9200', 'db_server_selection_timeout': '20000'}})
as_drone = <conftest.ApiAccessor object at 0x7faa89700b50>, as_public = <conftest.ApiAccessor object at 0x7faa89700b10>
api_db = Database(mongomock.MongoClient('mongodb://scitran-mongo:27017/scitran-integration?replicaSet=elasticflywheel', 27017), 'scitran-integration')

    def test_jwt_auth(config, as_drone, as_public, api_db):
        # try to login w/ unconfigured auth provider
        r = as_public.post('/login', json={'auth_type': 'ldap', 'code': 'test'})
>       assert r.status_code == 400
E       assert 401 == 400
E        +  where 401 = <Response at 0x7faa86a474d0 401 Unauthorized>.status_code

test/unit_tests/python/test_auth.py:11: AssertionError
-------------------------------------------------- Captured stderr setup ---------------------------------------------------
2017-05-17 20:43:48      scitran.api                config.py   117:DEBU Database(mongomock.MongoClient('mongodb://scitran-mongo:27017/scitran-integration?replicaSet=elasticflywheel', 27017), 'scitran-integration')
2017-05-17 20:43:48      scitran.api                config.py   126:DEBU Database(mongomock.MongoClient('mongodb://scitran-mongo:27017/logs-integration?replicaSet=elasticflywheel', 27017), 'logs-integration')
--------------------------------------------------- Captured stderr call ---------------------------------------------------
2017-05-17 20:43:49      scitran.api                  base.py    63:INFO Initialized request request_id=4f622ea6-1495053829
2017-05-17 20:43:49      scitran.api                config.py   222:INFO Initializing database, creating indexes
2017-05-17 20:43:49      scitran.api                config.py   254:INFO Persisting configuration
2017-05-17 20:43:49      scitran.api                  base.py   427:DEBU from local None POST /api/login {} request_id=4f622ea6-1495053829
=========================================== 1 failed, 30 passed in 2.30 seconds ============================================
kill: usage: kill [-s sigspec | -n signum | -sigspec] pid | jobspec ... or kill -l [sigspec]
```

**Comment by ambrussimon-invenshure** [comment]
@ryansanford Nope, it's related to the changes in the PR. That unit-test was assuming that the LDAP auth is completely unconfigured (eg. key not even present in `api.config.__config['auth']`), which is not true anymore. I can fix the test (get rid of it's assumption by pre-patching the config) tomorrow.

**Comment by ryansanford** [comment]
@ambrussimon-invenshure Perhaps the tests should igmore `SCITRAN_AUTH_CONFIG_FILE` if it's being set externally, since they should be completely self-contained?

**Comment by ryansanford** [comment]
Update to the group:
Ambrus has resolved the error with the unit tests, and that fix is represented in https://github.com/scitran/core/pull/789

There are 2 abao errors we are investigating now.

**Comment by ryansanford** [comment]
Unit test error was resolved with https://github.com/scitran/core/pull/789

Just force pushed rebase of this branch to integrate.

**Comment by ryansanford** [comment]
Testing with dependent repos has passed. Merging now.

**Pull request merged**
